on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.104.3'
    
    - name: Checkout repo on source_branch
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        # <<recommended if project uses git submodules for any purpose>>
        # <<required if deploying to git submodule directory>>
        token: ${{ secrets.REPO_TOKEN }}   # <<if needed for private repos>>
        fetch-depth: '0'
        # <<fetch-depth: '0' currently required until shallow clone problems are solved>>
        
    - name: Build site and push to release branch
      uses: aormsby/hugo-deploy-to-pages@v2.1
      id: build_step  # <<for outputs>>
      with:
        source_branch: 'main'
        release_branch: 'main'
        submodule_release_branch: 'main'
        # full_rebuild: true
        hugo_publish_directory: 'oakestra.github.io'   
        # hugo_build_options: '-D --minify --ignoreCache' <<hugo build cis customizable>>
        commit_message: "auto-website-build"
        # test_mode: true <<enable to run a few verification tests before your first live run>>

        # <<lots of other options!>>

    - name: Check if new build was made
      if: steps.build.outputs.was_new_build_created == 'true'
      run: echo "YAAASSSS new build."